<?php

namespace AppBundle\Repository;

/**
 * CountryClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryClassRepository extends \Doctrine\ORM\EntityRepository
{
}
